package com.esofa.crm.model;

public enum AuditEntryTypeE {

	INVENTORY_UPDATE,
	INITIATE_TRANSFER,
	ACCEPT_TRANSFER,
	CANCEL_TRANSFER,
	SALE, 
	SALE_VOIDED,
	RETURNED,
	ADD_STOCK,
	VOID_INVOICE,
	TRIAL_ADD,
	TRIAL_DELETE,
	TRIAL_UPDATE
}
